theme: jekyll-theme-slate

title: unconfigured - A Private Blog
description: because sharing helps

timezone: Europe/Berlin
paginate: 6

#pages:       
#  about: '/about/'
#  all posts: '/archive/'
#  github: 'https://github.com/unconfigured'

markdown: kramdown
kramdown:
  input:          GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
  - jekyll-paginate
