theme: jekyll-theme-slate

paginate: 1

title: unconfigured - A Private Blog

navbar-links:       
  about: '/about/'
  all posts: '/archive/'
  github: 'https://github.com/unconfigured'

plugins:
  - jekyll-paginate
