theme: jekyll-theme-slate

paginate: 1

title: unconfigured - A Private Blog
description: because sharing helps

#pages:       
#  about: '/about/'
#  all posts: '/archive/'
#  github: 'https://github.com/unconfigured'

plugins:
  - jekyll-paginate
